# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b688e604a4ff2477e59c6e59b662cedf48bc5f5a2ce0bb450b4eb8917a5ba05edadb8b17c2c7a9c10d9e29a7905163f5d8eb7ee8f41a7c742b845a0238497fa0

test:
  secret_key_base: fb6a70d0327820992df0e2bbb69c5ce26eda2422fbdda43104fc32031eebcd2d27bc0bf659c120887347ca8a4c807cbe94a802959b669c4d540fe92d1fbb1ecb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
